name: shop_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  responsive_sizer: ^3.3.1
  flutter_svg: ^2.0.10+1
  animated_notch_bottom_bar: ^1.0.3
  smooth_page_indicator: ^1.2.0
  flutter_floating_bottom_bar: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFPRODISPLAY
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBLACKITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
          weight: 400
        